Write-Host "BIENVENIDO A LA PIZZERIA BELLA NAPOLI"
[string]$x = Read-Host "PORFAVOR INDIQUE SI QUIERE UNA PIZZA VEGETARIANA O CLASICA"

If ($x -eq "VEGETARIANA") {
    Write-Host "ESTOS SON LOS INGREDIENTES A ELEGIR: PIMIENTO, TOFU"
    [string]$ingveg = Read-Host "ELIJA UNO DE LOS INGREDIENTES ANTES NOMBRADOS PORFAVOR"
    Write-Host "HA ELEGIDO UNA PIZZA VEGETARIANA FORMADA POR MOZARELLA, TOMATE Y $ingveg"
}ElseIf ($x -eq "CLASICA") {
    Write-Host "ESTOS SON LOS INGREDIENTES A ELEGIR: PEPERONI, JAMON Y SALMÓN"
    [string]$ingcla = Read-Host "ELIJA UNO DE LOS INGREDIENTES ANTES NOMBRADOS PORFAVOR"
    Write-Host "HA ELEGIDO UNA PIZZA CLASICA FORMADA POR MOZARELLA, TOMATE Y $ingcla"
}
